<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * InquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquiryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByKeyword($keyword)
    {
        $query = $this->createQueryBuilder('i')
            ->where('i.name Like :keyword')
            ->orWhere('i.tel Like :keyword')
            ->orWhere('i.email Like :keyword')
            ->orderBy('i.id', 'DESC')
            ->setParameters([
                ':keyword' => '%' . $keyword . '%'
            ])
            ->getQuery()
        ;
        return new ArrayCollection($query->getResult());
    }
}
