<?php
namespace AppBundle\Service\Csv;

use AppBundle\Entity\Inquiry;
use AppBundle\Repository\InquiryRepository;
use Doctrine\Common\Collections\ArrayCollection;

class InquiryCsvBuilderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InquiryCsvBuilder
     */
    private $SUT;

    /**
     * @var InquiryRepository
     */
    private $inquiryRepository;

    protected function setUp()
    {
        $this->inquiryRepository = $this->getMockBuilder(InquiryRepository::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->SUT = new InquiryCsvBuilder('UTF-8', $this->inquiryRepository);
//        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCSVが正しく作られること()
    {
        $inquiry1 = new Inquiry();
        $inquiry1->setId(1);
        $inquiry1->setName('TEST');
        $inquiry1->setEmail('foo@example.com');
        $inquiry2 = new Inquiry();
        $inquiry2->setId(2);
        $inquiry2->setName('TEST2');
        $inquiry2->setEmail('bar@example.com');
        $inquiryCollection = new ArrayCollection([$inquiry1,$inquiry2]);

        $this->inquiryRepository->expects($this->once())
            ->method('findAllByKeyword')
            ->willReturn($inquiryCollection)
        ;

        $result = $this->SUT->build('test');

        $expected = '1,TEST,foo@example.com'."\r\n".
            '2,TEST2,bar@example.com'."\r\n"
        ;

        $this->assertThat($result, $this->equalTo($expected));

    }


}