# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseSample
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'FirebaseSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
